//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace detskiysad__.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Parents
    {
        public int idParents { get; set; }
        public string FIO_Parents { get; set; }
        public string PassportNumber { get; set; }
        public string Phone_number { get; set; }
        public int idChildren { get; set; }
    
        public virtual Сhildren Children { get; set; }
    }
}
