//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace detskiysad__.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Reports
    {
        public int idReport { get; set; }
        public string FIO_Children { get; set; }
        public System.TimeSpan AttendanceTime { get; set; }
        public System.DateTime DateReport { get; set; }
    }
}
