//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace detskiysad__.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Сhildren
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Сhildren()
        {
            this.Parents = new HashSet<Parents>();
            this.Extra_class = new HashSet<Extra_class>();
        }
    
        public int idСhildren { get; set; }
        public byte[] ChildrenPhoto { get; set; }
        public string ChildrenSurname { get; set; }
        public string ChildrenName { get; set; }
        public string ChildrenPatronymic { get; set; }
        public System.DateTime ChildrenBirthday { get; set; }
        public string Birth_certificate { get; set; }
        public string Home_address { get; set; }
        public string SNILS { get; set; }
        public Nullable<int> idMenu { get; set; }
        public Nullable<int> IdGroup { get; set; }
    
        public virtual Group Group { get; set; }
        public virtual Menu Menu { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Parents> Parents { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Extra_class> Extra_class { get; set; }
    }
}
